#!/bin/bash
# End-of-Day Summary and Sync Script
# Called by Jarvis via cron job at 24:00 (00:00 next day)
# Checks git updates, summarizes progress, and pushes if needed

set -e

# Configuration
REPO_URL="${1:-https://github.com/uv-xiao/ainfra}"
LOCAL_REPO_PATH="${2:-/home/uvxiao/.openclaw/repos/ainfra}"
SCHEDULE_FILE="/home/uvxiao/.openclaw/agents/jarvis/workspace/LEARNING_SCHEDULE.md"
WORKSPACE_PATH="/home/uvxiao/.openclaw/agents/jarvis/workspace"
# Read from config file, fallback to hardcoded value
FEISHU_GROUP_ID=$(cat "$WORKSPACE_PATH/LEARNING_CONFIG.json" | python3 -c "import sys,json; print(json.load(sys.stdin)['feishu']['groupId'])" 2>/dev/null || echo "oc_922c749fb51de36a68f7b2f50eed20af")

# Get dates
TODAY=$(date +%Y-%m-%d)
YESTERDAY=$(date -d "yesterday" +%Y-%m-%d 2>/dev/null || date -v-1d +%Y-%m-%d 2>/dev/null)

# Function: Clone or update repo
sync_repo() {
    if [[ -d "$LOCAL_REPO_PATH/.git" ]]; then
        echo "Updating local repository..."
        cd "$LOCAL_REPO_PATH"
        git pull origin main 2>/dev/null || git pull origin master 2>/dev/null || true
    else
        echo "Cloning repository..."
        mkdir -p "$(dirname "$LOCAL_REPO_PATH")"
        git clone "$REPO_URL" "$LOCAL_REPO_PATH" --depth 100
        cd "$LOCAL_REPO_PATH"
    fi
}

# Function: Check for changes
has_changes() {
    local since_date="$1"
    
    cd "$LOCAL_REPO_PATH"
    
    # Fetch latest
    git fetch origin --quiet 2>/dev/null || true
    
    # Check for commits since yesterday
    local commits=$(git log --since="${since_date} 00:00:00" --until="${since_date} 23:59:59" --oneline origin/main 2>/dev/null | wc -l)
    
    if [[ "$commits" -gt 0 ]]; then
        echo "true"
    else
        echo "false"
    fi
}

# Function: Get commit summary
get_commit_summary() {
    local since_date="$1"
    
    cd "$LOCAL_REPO_PATH"
    
    echo "=== Commits on ${since_date} ==="
    git log --since="${since_date} 00:00:00" --until="${since_date} 23:59:59" --pretty=format:"• %s (%h)" origin/main 2>/dev/null || echo "No commits found"
    
    echo ""
    echo "=== Files Changed ==="
    git diff --name-only "$(git log --since="${since_date} 00:00:00" --until="${since_date} 23:59:59" --pretty=format:"%H" origin/main 2>/dev/null | tail -1)^..HEAD" 2>/dev/null || echo "No changes"
}

# Function: Count progress
get_progress_stats() {
    cd "$LOCAL_REPO_PATH"
    
    local notes_count=$(find notes -name "*.md" -not -path "*/templates/*" 2>/dev/null | wc -l)
    local exercises_count=$(find exercises -name "*.md" -not -path "*/templates/*" 2>/dev/null | wc -l)
    
    echo "NOTES=${notes_count}"
    echo "EXERCISES=${exercises_count}"
}

# Function: Check local uncommitted changes
check_local_changes() {
    cd "$LOCAL_REPO_PATH"
    
    if [[ -n $(git status --porcelain 2>/dev/null) ]]; then
        echo "true"
    else
        echo "false"
    fi
}

# Function: Auto-commit and push local changes
auto_push_changes() {
    cd "$LOCAL_REPO_PATH"
    
    if [[ "$(check_local_changes)" == "true" ]]; then
        echo "Found local uncommitted changes. Auto-committing..."
        
        git add -A
        git commit -m "chore: auto-sync daily progress $(date +%Y-%m-%d)" -m "Auto-generated by Jarvis EOD summary"
        
        if git push origin main 2>/dev/null || git push origin master 2>/dev/null; then
            echo "✅ Successfully pushed changes"
            return 0
        else
            echo "⚠️ Failed to push changes"
            return 1
        fi
    else
        echo "No local changes to push"
        return 0
    fi
}

# Function: Get yesterday's topic
get_yesterday_topic() {
    local date_str="$1"
    
    awk -v date="$date_str" '
        /^\| [0-9]+ \|/ {
            if ($3 == date) {
                gsub(/^[ \t]+|[ \t]+$/, "", $4)
                print $4
                exit
            }
        }
    ' "$SCHEDULE_FILE" 2>/dev/null || echo "Unknown"
}

# Function: Build summary message
build_summary() {
    local has_changes="$1"
    local topic="$2"
    local stats="$3"
    local commits_info="$4"
    local auto_pushed="$5"
    
    local notes_count=$(echo "$stats" | grep "^NOTES=" | cut -d= -f2)
    local exercises_count=$(echo "$stats" | grep "^EXERCISES=" | cut -d= -f2)
    
    cat <<EOF
📊 **End-of-Day Learning Summary** - ${YESTERDAY}

📚 **Yesterday's Topic:** ${topic}

EOF

    if [[ "$has_changes" == "true" ]]; then
        echo "✅ **Progress detected!**"
        echo ""
        echo "$commits_info"
        echo ""
    else
        echo "⚠️ **No commits detected yesterday**"
        echo ""
        echo "Don't forget to commit your notes and exercises!"
        echo ""
    fi
    
    cat <<EOF
📈 **Current Progress:**
• Notes created: ${notes_count}
• Exercises completed: ${exercises_count}

EOF

    if [[ "$auto_pushed" == "true" ]]; then
        echo "🤖 **Auto-push:** Local changes were automatically committed and pushed"
        echo ""
    elif [[ "$(check_local_changes)" == "true" ]]; then
        echo "⚠️ **Uncommitted changes detected** but auto-push failed or was disabled"
        echo "Please manually commit and push your changes."
        echo ""
    fi
    
    cat <<EOF
🎯 **Tomorrow's Preview:**
Check tomorrow's topic with: \`@jarvis what's tomorrow's plan?\`

Keep up the great work! 🚀
EOF
}

# Function: Update progress tracking
update_progress_tracking() {
    local date_str="$1"
    
    # This would update checkboxes in LEARNING_SCHEDULE.md
    # For now, just output what would be updated
    echo "Progress tracking update for ${date_str}:"
    echo "- Would mark Day X as complete"
    echo "- Would update statistics"
}

# Main execution
main() {
    echo "=== End-of-Day Summary and Sync ==="
    echo "Yesterday: $YESTERDAY"
    echo "Today: $TODAY"
    echo ""
    
    # Sync repository
    sync_repo
    
    # Get yesterday's topic
    local yesterday_topic=$(get_yesterday_topic "$YESTERDAY")
    
    # Check for remote changes
    local changes=$(has_changes "$YESTERDAY")
    
    # Get commit info if there are changes
    local commits_info=""
    if [[ "$changes" == "true" ]]; then
        commits_info=$(get_commit_summary "$YESTERDAY")
    fi
    
    # Get progress stats
    local stats=$(get_progress_stats)
    
    # Auto-push local changes if any
    local auto_pushed="false"
    if [[ "$(check_local_changes)" == "true" ]]; then
        if auto_push_changes; then
            auto_pushed="true"
        fi
    fi
    
    # Build summary message
    local summary=$(build_summary "$changes" "$yesterday_topic" "$stats" "$commits_info" "$auto_pushed")
    
    echo "=== SUMMARY MESSAGE ==="
    echo "$summary"
    echo ""
    echo "=== END SUMMARY ==="
    
    # Update progress tracking
    update_progress_tracking "$YESTERDAY"
}

main "$@"
